### ISSUE TITLE
Cannot find module npmlog during install

### ISSUE THREAD

**Issue by ghost** [wakatime/c9-wakatime#5]
I've tried to install wakatime on a new C9 workspace. At first, this error came up:

```
gbhojraj:~/workspace $ c9 install wakatime --force
module.js:327
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /mnt/shared/sbin/npm:18:11
    at Object.<anonymous> (/mnt/shared/sbin/npm:75:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
Command failed: /mnt/shared/sbin/npm
```

**Comment by seantomburke** [comment]
Having the same issue^

**Comment by alanhamlett** [comment]
This is a different error message, but does following the steps in #2 help? If not, nothing has changed in the plugin so may be worth opening an issue with Cloud9:
https://groups.google.com/forum/#!forum/cloud9-sdk

**Comment by carl-parrish** [comment]
Running into the same issue.

**Comment by alanhamlett** [comment]
These new install instructions should help:
https://github.com/wakatime/c9-wakatime#installation

(Thanks to Luciendub https://community.c9.io/t/allow-wakatime-in-normal-mode/14815)

**Comment by JessePotterMusic** [comment]
I'm having this same issue ever since upgrading npm. I actually can't use npm commands at all anymore.  Is there a way I can create the files that are missing?
